services:
  postgres:
    container_name: demo-nestjs-postgres
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - "5455:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: backend
